"""
Django settings for pioner_gallery project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-67@a+5%1pcha0*u#_dwcz_7pb17q2#+_x7#4n3(4%yp$b1ap8('

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False
DEBUG = True

# Allowed hosts on pythonanywhere:
# ALLOWED_HOSTS = ['yamadasan.mysql.pythonanywhere-services.com', 'yamadasan.pythonanywhere.com']
#
# Allowed hosts on local:
ALLOWED_HOSTS = ['127.0.0.1']
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'your_app_name': {  # Replace 'your_app_name' with the name of your app or __name__ for current module
            'handlers': ['file'],
            'level': 'DEBUG',
        },
    },
}

# Application definition
INSTALLED_APPS = [
    'django_extensions',
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Current webapp app:
    'pioner_gallery.webapp',
    'pioner_gallery.blog',
    'pioner_gallery.user_login',
    'pioner_gallery.mediaplanner',
    'pioner_gallery.marketplace',
    # 'pioner_gallery.templatetags',
    # 'django-allauth',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'ckeditor',
    # 'pioner_gallery.user_login.apps.UserLoginConfig.name',
    # 'allauth.account.auth_backends.AuthenticationBackend',
]

default_app_config = 'pioner_gallery.user_login.apps.UserLoginConfig'

# https://stackoverflow.com/questions/63260580/how-to-fix-this-error-no-module-named-allauth
# AUTHENTICATION_BACKENDS = (
#     "django.contrib.auth.backends.ModelBackend",
#     "allauth.account.auth_backends.AuthenticationBackend",
# )
MIDDLEWARE = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
]

ROOT_URLCONF = 'pioner_gallery.urls'

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': 800,
    },
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #        'DIRS': [BASE_DIR, 'pioner_gallery', 'templates']
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        #        'DIRS': ['/home/yamadasan/pioner-gallery/pioner_gallery/templates/pioner_gallery/'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'pioner_gallery.user_login.context_processors.user_profile',
            ],
        },
    },
]

WSGI_APPLICATION = 'pioner_gallery.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DB FOR PYTHONANYWHERE:
#
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.mysql",
#         "NAME": "yamadasan$mysqlanywhere",
#         "USER": "yamadasan",
#         "PASSWORD": "somepass",
#         "HOST": "yamadasan.mysql.pythonanywhere-services.com",
#         "PORT": "3306",
#     }
# }

# DB FOR LOCAL TESTING:
#
# DB FOR LOCAL TESTING WITH DOCKER:
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "yamadasan$mysqlanywhere",
        "USER": "yamadasan",
        "PASSWORD": "somepass",
        'HOST': '127.0.0.1',  # Use the service name of the MySQL container
        "PORT": "3306",
    }
}

# Issues resolution advisory:
# https://chat.openai.com/share/5c83716a-f380-4e78-b198-ae0494f20795


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/staticfiles/'
# STATIC_URL = '/home/yamadasan/pioner-gallery/pioner_gallery/staticfiles/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
print('MEDIA_ROOT: ', MEDIA_ROOT)
print('MEDIA_URL: ', MEDIA_URL)
